### ISSUE TITLE
does support ap mode and bluetooth working same time on cm4 with wireless module onboard?

### ISSUE THREAD

**Issue by ddtramp** [WLAN-Pi/wlanpi-hotspot#13]
1. respberry cm4 with wireless module onboard
2. start ap mode
3. use bluetooth connect device

???

**Comment by jiribrejcha** [comment]
Yes, it does, in theory. But we disable onboard CM4 (and RPi4) Wi-Fi adapter by default. Why? Because it doesn’t support Monitor mode, and because we want the M.2 hours (or USB) adapter with Monitor mode support to always become wlan0 device. 

If you want to experiment and enable the onboard adapter, you can do so by removing this line `dtoverlay=disable-wifi` in the CM4 section of this config file `/boot/config.txt`. Then reboot. 

If you want to use the M.2 (or USB adapter) in AP mode and Bluetooth at the same time, that should work with no tweaks.
